POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Gt1",
    "number": "123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Gt1"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "ADa Lovelace",
    "number": "123456"
}