POST http://localhost:3106/api/persons
Content-Type: application/json

{
    "name": "Gt1",
    "number": "123456"
}

###
POST http://localhost:3106/api/persons
Content-Type: application/json

{
    "name": "gT1",
    "number": "123456"
}

###
POST http://localhost:3106/api/persons
Content-Type: application/json

{
    "name": "Gt1"
}

###
POST http://localhost:3106/api/persons
Content-Type: application/json

{
    "name": "ADa Lovelace",
    "number": "123456"
}

###
POST http://localhost:3106/api/persons
Content-Type: application/json

{
    "name": "G1",
    "number": "123456"
}

###
POST http://localhost:3106/api/persons
Content-Type: application/json

{
    "name": "G353",
    "number": "343-45545345"
}
